### ISSUE TITLE
wrong homepage field in package.json

### ISSUE THREAD

**Issue by jricaldi** [jonschlinkert/diacritics-map#1]
It's a really very very tiny minor issue, actually, I didn't sure if this applies to issue

![image](https://user-images.githubusercontent.com/2177405/33449657-63b803a4-d5d7-11e7-9fe4-d8f7d7bdaa17.png)

should be "homepage": "https://github.com/jonschlinkert/diacritics-map"

**Comment by jonschlinkert** [comment]
thanks, want to do a pr?

**Comment by doowb** [comment]
Closed by #2
